version: '2'
services:
  php_apache:
    image: php:7.4-apache
    container_name: php_74_apache_magento2
    env_file:
      - .env
    ports:
      - '80:80'
    volumes:
      - '../src:/var/www/html:rw'
    mem_limit: '6000m'
    build:
      context: ../
      dockerfile: build/app/Dockerfile
    networks:
      - sabay_docker

networks:
  sabay_docker:
    external: true